[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"

[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63073000; includeSubDomains; preload"
